import type { Metadata } from "next";
import { ReactNode } from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type LayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <div className="flex flex-col justify-between min-h-screen">
      <header>Header</header>
      <main className="flex-grow">{children}</main>
      <footer>footer</footer>
    </div>
  );
}
