import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: {
    template: '%s | Just Ben UK',
    default: 'Just ben UK'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
